name: faulty_vaulty
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  file_picker: ^5.5.0
  fluttertoast: ^8.2.2
  flutter:
    sdk: flutter
  open_file: ^3.3.2
  permission_handler: ^10.4.3
  path_provider: ^2.1.1
  photo_manager: ^2.7.1
  provider: ^6.0.5
  path: ^1.8.3
  simple_circular_progress_bar: ^1.0.2
  tab_indicator_styler: ^2.0.0
  video_thumbnail: ^0.5.3
  transparent_image: ^2.0.1
  get: ^4.6.6
  iconsax:
  mime: 


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
